# Generated by Django 3.2.25 on 2026-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
