# Generated by Django 3.2.25 on 2026-06-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_cost',
            new_name='delivery_cost',
        ),
    ]
