# Generated by Django 6.0.6 on 2026-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_deliver_cost_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='size_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
